### ISSUE TITLE
On macOs not all changes are picked up

### ISSUE THREAD

**Issue by bric3** [gradle/native-platform#269] opened 2021-01-11 11:53 UTC
Hi,

I have been playing with the file-events 0.22-milestone-10 and I didn't understood why changes in an intellij log file wasn't picked up with my code, so I ran the test-app code, but the problem appears to be the same.

So I'm trying to watch changes in this file `/Users/bric3/Library/Logs/JetBrains/IntelliJIdea2020.3/idea.log`, I ran `net.rubygrapefruit.platform.test.Main.main` with `/Users/bric3/Library/Logs/JetBrains/IntelliJIdea2020.3` as it seems the macOs file event watcher cannot wath specific files. But the watcher do not pick up changes, while running a simple `tail` works as expected.

Howver I noted that if I modify the file myself, changes aredetected and reported to the handler.
```
echo test >> /Users/bric3/Library/Logs/JetBrains/IntelliJIdea2020.3/idea.log
```

----

Running Big Sur 11.1, on Java 15.0.1 (Corretto)

```
$ sw_vers
ProductName:	macOS
ProductVersion:	11.1
BuildVersion:	20C69
$ uname -a
Darwin <edited> 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64
```

**Comment by lptr** [comment] 2021-01-11 11:58
IIUC `echo test >> ...` is picked up by the file watcher. What are the changes that are not picked up by the file watcher?

**Comment by bric3** [comment] 2021-01-11 11:59
@lptr Log messages appended by IntlliJ IDEA are not reported.

**Comment by lptr** [comment] 2021-01-11 12:01
I wonder what mechanism `tail` uses to watch for file changes. Can it be that the changes are not flushed to the file system yet, but `tail` is already notified?

Can you reproduce this issue with any other way apart from the IntelliJ log file?

**Comment by lptr** [comment] 2021-01-11 12:01
Does the watcher get notified when you exit IntelliJ?

**Comment by bric3** [comment] 2021-01-11 12:02
@lptr Just tried, it doesn't seem to be the case. I really get nothing.

**Comment by lptr** [comment] 2021-01-11 12:03
Hm. Are there any symlinks in the path along `/Users/bric3/Library/Logs/JetBrains/IntelliJIdea2020.3/idea.log`?

**Comment by bric3** [comment] 2021-01-11 12:04
None

**Comment by lptr** [comment] 2021-01-11 12:04
OK, so maybe it's something about the OS not updating the file system for every appended line, yet notifying `tail` via some other mechanism?

**Comment by bric3** [comment] 2021-01-11 12:05
@lptr Could be, even `gtail` (the core-utils port on OSX) can follow changes.

**Comment by bric3** [comment] 2021-01-11 13:35
I'm not quite sure how `tail` works, they don't seem to import `CoreServices/CoreServices.h`, but [`sys/event.h`](https://opensource.apple.com/source/xnu/xnu-1456.1.26/bsd/sys/event.h.auto.html) / [`sys/cdefs.h`](https://opensource.apple.com/source/xnu/xnu-1456.1.26/bsd/sys/cdefs.h.auto.html)

`tail` source are here : https://opensource.apple.com/source/text_cmds/text_cmds-106/tail/


And more interestingly here's the code that _follows_ the file : [`forward.c`](https://opensource.apple.com/source/text_cmds/text_cmds-106/tail/forward.c.auto.html), the code seems to be using kqueue.

```c
static void
set_events(file_info_t *files)
{
	int i, n = 0;
	file_info_t *file;
	struct timespec ts;
	struct statfs sf;

	ts.tv_sec = 0;
	ts.tv_nsec = 0;

	action = USE_KQUEUE;
	for (i = 0, file = files; i < no_files; i++, file++) {
		if (! file->fp)
			continue;

		if (fstatfs(fileno(file->fp), &sf) == 0 &&
		    (sf.f_flags & MNT_LOCAL) == 0) {
			action = USE_SLEEP;
			return;
		}

		if (Fflag && fileno(file->fp) != STDIN_FILENO) {
			EV_SET(&ev[n], fileno(file->fp), EVFILT_VNODE,
			    EV_ADD | EV_ENABLE | EV_CLEAR,
			    NOTE_DELETE | NOTE_RENAME, 0, 0);
			n++;
		}
		EV_SET(&ev[n], fileno(file->fp), EVFILT_READ,
		    EV_ADD | EV_ENABLE | EV_CLEAR, 0, 0, 0);
		n++;
	}

	if (kevent(kq, ev, n, NULL, 0, &ts) < 0) {
		action = USE_SLEEP;
	}
}

/*
 * follow -- display the file, from an offset, forward.
 *
 */
void
follow(file_info_t *files, enum STYLE style, off_t off)
{
	int active, i, n = -1;
	struct stat sb2;
	file_info_t *file;
	struct timespec ts;

	/* Position each of the files */

	file = files;
	active = 0;
	n = 0;
	for (i = 0; i < no_files; i++, file++) {
		if (file->fp) {
			active = 1;
			n++;
			if (no_files > 1 && !qflag)
				(void)printf("\n==> %s <==\n", file->file_name);
			fname = file->file_name;
			forward(file->fp, style, off, &file->st);
			fname = NULL;
			if (Fflag && fileno(file->fp) != STDIN_FILENO)
			    n++;
		}
	}
	if (! active)
		return;

	last = --file;

	kq = kqueue();
	if (kq < 0)
		err(1, "kqueue");
	ev = malloc(n * sizeof(struct kevent));
	if (! ev)
	    err(1, "Couldn't allocate memory for kevents.");
	set_events(files);

	for (;;) {
		for (i = 0, file = files; i < no_files; i++, file++) {
			if (! file->fp)
				continue;
			if (Fflag && file->fp && fileno(file->fp) != STDIN_FILENO) {
				if (stat(file->file_name, &sb2) == 0 &&
				    (sb2.st_ino != file->st.st_ino ||
				     sb2.st_dev != file->st.st_dev ||
				     sb2.st_nlink == 0)) {
					show(file);
					file->fp = freopen(file->file_name, "r", file->fp);
					if (file->fp == NULL) {
						ierr();
						continue;
					} else {
						memcpy(&file->st, &sb2, sizeof(struct stat));
						set_events(files);
					}
				}
			}
			show(file);
		}

		switch (action) {
		case USE_KQUEUE:
			ts.tv_sec = 1;
			ts.tv_nsec = 0;
			/*
			 * In the -F case we set a timeout to ensure that
			 * we re-stat the file at least once every second.
			 */
			n = kevent(kq, NULL, 0, ev, 1, Fflag ? &ts : NULL);
			if (n < 0)
				err(1, "kevent");
			if (n == 0) {
				/* timeout */
				break;
			} else if (ev->filter == EVFILT_READ && ev->data < 0) {
				 /* file shrank, reposition to end */
				if (lseek(ev->ident, (off_t)0, SEEK_END) == -1) {
					ierr();
					continue;
				}
			}
			break;

		case USE_SLEEP:
			(void) usleep(250000);
			break;
		}
	}
}
```

**Comment by lptr** [comment] 2021-01-11 13:47
Can you check if the changes are picked up by some other file system watcher using directory watching, like `watchman`?

This guy has support on macOS for watching via both `CoreServices` and `kqueue`: https://github.com/emcrisostomo/fswatch. So I guess you get different results that way.

I think if you are watching a file specifically you'll get different events than if you are watching a directory. Basically, in the former case you are notified of file content changes, and in the latter about directory entry changes. File system caching could mean the difference between these events.

**Comment by bric3** [comment] 2021-01-11 14:01
Whn watching the file directly

```shell
$ fswatch --monitor=fsevents_monitor /Users/bric3/Library/Logs/JetBrains/IntelliJIdea2020.3/idea.log
^C%
$ fswatch --monitor=kqueue_monitor /Users/bric3/Library/Logs/JetBrains/IntelliJIdea2020.3/idea.log
/Users/bric3/Library/Logs/JetBrains/IntelliJIdea2020.3/idea.log
/Users/bric3/Library/Logs/JetBrains/IntelliJIdea2020.3/idea.log
/Users/bric3/Library/Logs/JetBrains/IntelliJIdea2020.3/idea.log
/Users/bric3/Library/Logs/JetBrains/IntelliJIdea2020.3/idea.log
/Users/bric3/Library/Logs/JetBrains/IntelliJIdea2020.3/idea.log
/Users/bric3/Library/Logs/JetBrains/IntelliJIdea2020.3/idea.log
/Users/bric3/Library/Logs/JetBrains/IntelliJIdea2020.3/idea.log
/Users/bric3/Library/Logs/JetBrains/IntelliJIdea2020.3/idea.log
/Users/bric3/Library/Logs/JetBrains/IntelliJIdea2020.3/idea.log
/Users/bric3/Library/Logs/JetBrains/IntelliJIdea2020.3/idea.log
/Users/bric3/Library/Logs/JetBrains/IntelliJIdea2020.3/idea.log
^[/Users/bric3/Library/Logs/JetBrains/IntelliJIdea2020.3/idea.log
/Users/bric3/Library/Logs/JetBrains/IntelliJIdea2020.3/idea.log
^C%
```

It seems that kqueue is picking the events but not core fs events.


And when watching a directory

```
$ fswatch --monitor=fsevents_monitor /Users/bric3/Library/Logs/JetBrains/IntelliJIdea2020.3
/Users/bric3/Library/Logs/JetBrains/IntelliJIdea2020.3/idea.log
^C%
```

FS events only picks events when touching or appending via a command line tool (`touch` or `echo "" >> `).

```
$ fswatch --monitor=kqueue_monitor /Users/bric3/Library/Logs/JetBrains/IntelliJIdea2020.3
^C%
```

kqueue don't pick up anything, even when the file modified with a command line tool (`touch` or `echo "" >> `).

THere are other options in this tool that I didn't explored yet.

----

Quick question how to enalble the logger, I have tried to set `Logger.getLogger(NativeLogger.class.getName()).setLevel(Level.ALL);` before creating the file event watcher, but I don't see any logs appearing.

**Comment by bric3** [comment] 2021-01-11 14:29
Also no luck to get watchman working. I did take a look at [`fsnotifier` the native file watcher of intellij]https://github.com/JetBrains/intellij-community/blob/master/native/fsNotifier/mac/fsnotifier.c), but I cannot make it work either.

**Comment by lptr** [comment] 2021-01-11 15:58
Yeah, the logger is a weird thing. You have to also call `AbstractFileEventFunctions.invalidateLogLevelCache()` once you set the log level or you have to wait a second for the native-side "cache" to time out.

Please not that all of these APIs are considered internal, and not for public consumption for now. A nice way to configure logging is one of the things that held us back from adding a public API (or releasing 0.22 GA).

All that said, it seems that what we do in `native-platform` is exactly what you can achieve with macOS file system events, and that's good enough for the goals we have (which is primarily to support the Gradle build tool's file system watching). I also don't think it would be feasible to subscribe to each and every file's changes via `kqueue` in any non-trivial build. I think the two kernel APIs are useful for fundamentally different purposes.

I'm going to close this now with _working as intended._ Thanks for tracking down the difference with `kqueue`.

**Closed by lptr** 2021-01-11 15:58 UTC
Labels: @execution

**Comment by bric3** [comment] 2021-01-11 16:20
Hi yes, I'm just experimenting, I understand this is still under developement. I understand the consequences of using internal APIs ;)

Thanks following up quickly on this issue. I'm a bit sad as was hoping native-platform could solve the use case my project requires due to how fsevent appear to work, indeed both systems appear to target different needs, but I understand your point and focus on the build requirement.

Although I believe this difference should be documented though, as it may confuse users. (Another example is that the file event watcher requires to work with a directory instead of a regular file on macOs).

Anyway, many thanks for the quick answers.

**Comment by lptr** [comment] 2021-01-11 20:09
Yes, we should definitely document this once we add a public API and documentation to the feature.

BTW, if you have more questions, we have a `#file-system-watching` channel on the Gradle community Slack here: gradle-community.slack.com

**Comment by bric3** [comment] 2021-01-12 08:37
Cool, thanks for the tip !
